name: Build and deploy ASP.Net Core API to Azure Web App - Finflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore API
        run: dotnet restore ./FinFlow.API/FinFlow.API.csproj

      - name: Build API
        run: dotnet build ./FinFlow.API/FinFlow.API.csproj --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ./FinFlow.API/FinFlow.API.csproj --configuration Release --no-build --output "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4416FD814BEF47189ABADFA6B9964AFB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4F4DC1F0310546138FC015914E60BB5C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_10C947F5430D4A12A7D00B172A68EBC3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: Finflow
          slot-name: Production
          package: .